baseURL = 'https://be-curious.prime-kobo.com'
languageCode = 'ja'
title = '好奇心大事だよ？'
theme = "ananke"
resourceDir = "./resources"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.ja]
    title = "好奇心大事だよ？"
    weight = 2
    contentDir = "content/ja"
  [languages.en]
    title = "Curiosity is important, isn't it?"
    weight = 2
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "white"
  author = "Masaru Kitajima"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
